# https://hub.docker.com/_/python/
ARG PY_VERSION=3.13
ARG PY_IMG_VERSION=slim-bullseye
FROM python:${PY_VERSION}-${PY_IMG_VERSION}

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=yes \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

WORKDIR /usr/src/app

RUN apt-get update

RUN apt-get install -y \
    build-essential \ 
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-cffi \
    shared-mime-info \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

ARG WHEEL_PATH=./api-lib/dist/api_lib-0.1.0-py3-none-any.whl
COPY ${WHEEL_PATH} /tmp/api_lib-0.1.0-py3-none-any.whl
RUN pip install /tmp/api_lib-0.1.0-py3-none-any.whl

COPY ./metadata/pyproject.toml ./

RUN pip install -e .
RUN pip install -e .[test]

ARG PY_VERSION
RUN find /usr/local/lib/python${PY_VERSION} -name '*.c' -delete \
    && find /usr/local/lib/python${PY_VERSION} -name '*.pxd' -delete \
    && find /usr/local/lib/python${PY_VERSION} -name '*.pyd' -delete \
    && find /usr/local/lib/python${PY_VERSION} -name '__pycache__' | xargs rm -r

COPY . .

EXPOSE ${PORT}