apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: tasks
    spec:
      containers: 
      - name: tasks
        image: $CONTAINER_REGISTRY/$NAME:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8000"
        - name: AUDIENCE
          value: ${AUDIENCE}
        - name: SECRET
          value: ${SECRET}
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_BACKEND_URL
          value: "redis://redis:6379/0"
        - name: POSTGRES_URL
          value: $POSTGRES_URL
        - name: LIFETIME_SECONDS
          value: "${LIFETIME_SECONDS}"
        - name: DBNAME
          value: ${DBNAME}
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: capcom
---
apiVersion: v1
kind: Service
metadata:
  name: tasks
spec:
  selector:
    app: tasks
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000