apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-init
  namespace: observability
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          mc alias set minio http://minio:9000 minioadmin minioadmin123
          mc mb minio/loki-chunks --ignore-existing
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-minio
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          until nc -z minio 9000; do
            echo "Waiting for MinIO..."
            sleep 2
          done