name: integration
on:
  push:
    branches:
      - test
    paths:
      - metadata/**
      - tasks/**
  workflow_dispatch:
jobs:
  test-integration:
    name: Run Integration Tests with Cypress
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: ${{ vars.FRONTEND_URL }}
    strategy:
      matrix:
        node: [18]
        browser: [chrome]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack and set Yarn version 4.9.1
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: ${{ matrix.browser }}
          headed: false
          record: true
          quiet: false # https://github.com/marketplace/actions/cypress-io#quiet-flag
          config-file: cypress.config.js
          tag: node-${{ matrix.node }}
          # auto-cancel-after-failures: 10 #Cancel run after 2 failed tests (only available in paid plans)
        env:
          CYPRESS_DEV_USERNAME: ${{ vars.CYPRESS_DEV_USERNAME }}
          CYPRESS_DEV_PASSWORD: ${{ secrets.CYPRESS_DEV_PASSWORD }}
          CYPRESS_BASE_URL: ${{ vars.FRONTEND_URL }}
          CYPRESS_PROJECT_ID: 3ewdr4 # Cypress Cloud project ID as env variable or store in Cypress config file
          CYPRESS_RECORD_KEY: e20fa464-ce7d-45f1-b58c-asd4r23rwe # Cypress Cloud record key as an env var